In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
#Import Dataset

ds= pd.read_csv(r"C:\Users\nivesan\Downloads\Churn_Modelling.csv")
ds.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
#Analysing the data using pandas and Checking if the dataset contains any null values
ds.info()
ds.isnull().any() #o nullvalues

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [4]:
#Splitting data as independent and dependent #removing index column in independent dataset
x=ds.iloc[:,1:31]. values
y=ds.iloc[:,-1].values
print(x,y)


[[15634602 'Hargrave' 619 ... 1 101348.88 1]
 [15647311 'Hill' 608 ... 1 112542.58 0]
 [15619304 'Onio' 502 ... 0 113931.57 1]
 ...
 [15584532 'Liu' 709 ... 1 42085.58 1]
 [15682355 'Sabbatini' 772 ... 0 92888.52 1]
 [15628319 'Walker' 792 ... 0 38190.78 0]] [1 0 1 ... 1 1 0]


In [8]:
#splitting data into train and test
from sklearn.model_selection import train_test_split
df = pd.read_csv(r"C:\Users\nivesan\Downloads\Churn_Modelling.csv")
x= df.iloc[:,6:8].values
y=df.iloc[:,3].values
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.05, random_state=0)

In [9]:
print (x_train)

[[42  9]
 [40  7]
 [46  9]
 ...
 [35  5]
 [38  9]
 [48  1]]


In [10]:
print (y_train)

[601 844 743 ... 738 590 623]


In [11]:
print (x_test)

[[35  8]
 [40  2]
 [42  8]
 [32  4]
 [38  5]
 [57  3]
 [34  0]
 [29  6]
 [64  9]
 [63  1]
 [31 10]
 [45  8]
 [33  4]
 [31  9]
 [51  9]
 [55  9]
 [43  9]
 [66  5]
 [30  4]
 [45  6]
 [42  7]
 [35  2]
 [34  4]
 [34  2]
 [35  6]
 [46  1]
 [29  2]
 [30 10]
 [29  9]
 [44  4]
 [34  3]
 [41  5]
 [29  9]
 [64  6]
 [36  6]
 [24  2]
 [38  5]
 [27  5]
 [36  8]
 [35  4]
 [34  7]
 [41  7]
 [55  2]
 [24  6]
 [42  6]
 [29  5]
 [41  6]
 [29  8]
 [50  1]
 [27  0]
 [55  0]
 [22  8]
 [35  4]
 [60  6]
 [72  5]
 [33 10]
 [41  9]
 [39  6]
 [45  5]
 [40  3]
 [42  0]
 [45  4]
 [38  8]
 [38  7]
 [47  9]
 [54  9]
 [44  6]
 [41  3]
 [24  2]
 [56  9]
 [65  9]
 [35  8]
 [29  7]
 [63  3]
 [41  5]
 [25  8]
 [54  4]
 [32  7]
 [27  6]
 [39  2]
 [57  5]
 [57  9]
 [23  5]
 [41  9]
 [70  9]
 [67  1]
 [32  3]
 [37  9]
 [39  3]
 [38  7]
 [40  1]
 [44  6]
 [39  4]
 [38  5]
 [33  4]
 [65  2]
 [31  1]
 [28  6]
 [40  5]
 [28  5]
 [22  4]
 [35  3]
 [39  2]
 [33  0]
 [47  7]
 [35  8]
 [28  7]
 [38  8]
 [45  6]
 [31  1]
 [38  5]
 

In [13]:
print (x_train)

[[42  9]
 [40  7]
 [46  9]
 ...
 [35  5]
 [38  9]
 [48  1]]
