# Basic python

# 1.Split this String

In [1]:
single="hi there sam!"
print(single)
tokens=single.split()
print(tokens)



hi there sam!
['hi', 'there', 'sam!']


In [2]:
hello="i am studying"
print(hello)
hi=hello.split()
print(hi)


i am studying
['i', 'am', 'studying']


# 2.Use .format() to print the following string

output should be:The diameter of earth is 12742

In [6]:
planet="Earth"
diameter=12742

In [7]:
print('the diameter of {} is {} kilometers.' . format(planet,diameter));

the diameter of Earth is 12742 kilometers.


# 3.In this nest dictionary grab the world"hello" 

In [41]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
print(lst[3][1][2][0])

hello


In [31]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


In [9]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


# 4.1 Create an array of 10 zeros?

# 4.2 Create an array of 10 fives?

In [10]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
import numpy as np
array=np.ones(10)*5
print("An array of  fives:")
print(array)

An array of  fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# 5.Create an array of all the even integers from 20 to 35

In [13]:
import numpy as np
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


# 6.Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 7.Concatenate a and b

 a=np.array([1,2,3]),b=np.array([4,5,6])

In [15]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)

[5 7 9]


# 8.Create a database with 3 rows and 2 columns

In [1]:
import pandas as pd
data = [['tom',15], ['jerry',20], ['juli',23]]
df = pd.DataFrame(data, columns=['Name','Age'])
print(df)

    Name  Age
0    tom   15
1  jerry   20
2   juli   23


In [2]:
import pandas as pd
data = [['yosh',15], ['vicky',21], ['maddy',19]]
df = pd.DataFrame(data, columns=['players','numbers'])
print(df)

  players  numbers
0    yosh       15
1   vicky       21
2   maddy       19


# 9.Generate the series of dates from 1st jan,2023 to 10th feb,2023

In [26]:
import pandas as pd
pd.date_range("01-01-23","10-02-23")

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

# 10. Create 2D list to DataFrame
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [3]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]