###### Basic Python

## 1. Split this string

In [1]:
single = "Hi there Sam!"
print(single)
tokens= single.split()
print(tokens)


Hi there Sam!
['Hi', 'there', 'Sam!']


In [3]:
hello="i am studying"
print(hello)
hi=hello.split()
print(hi)

i am studying
['i', 'am', 'studying']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742


In [5]:
print('the diameter of {} is {} kilometers.' . format(planet,diameter));

the diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [17]:
d = ['hello']

# Numpy

In [15]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [16]:
import numpy as np
array=np.zeros(10)
print ("an array of 10 zeros")
print(array)

an array of 10 zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
import numpy as np
array=np.ones(10)*5
print("an array of fives")
print(array)

an array of fives
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [15]:
import numpy as np 
array=np.arange(20,35,2)
print("array of all the even integers from 20 to 35")
print(array)

array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
import numpy as np 
array=np.arange(0,9).reshape (3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [2]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=a+b
print(c)

[5 7 9]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [4]:

import pandas as pd
data = [['tom', 10], ['nick', 15], ['juli', 14]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
print(df)

   Name  Age
0   tom   10
1  nick   15
2  juli   14


In [5]:
import pandas as pd
data = [['man', 10], ['sim', 15], ['rahul', 14]]
df = pd.DataFrame(data, columns=['players', 'numbers'])
print(df)

  players  numbers
0     man       10
1     sim       15
2   rahul       14


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [7]:
import pandas as pd 
pd.date_range("01-01-23","10-02-23")

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [7]:
 import numpy as np
 lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
 df= np.Dataframe(lists)
 df.columns = ['col_1', 'col_2', 'col_3'  ]
 print(df)

AttributeError: module 'numpy' has no attribute 'Dataframe'